#' @export
print.crumble <- function(x, ...) {
	d <- cli::cli_div(theme = list(rule = list("line-type" = "double")))
	cli::cli_rule(left = "Results {.fn crumble}")
	cli::cli_end(d)
	cli::cli_h3("{.emph Average Treatment Effect}")
	cli::cli_text(cat("      "), "{.strong Estimate}: {round(x$ate, 4)}")
	cli::cli_text(cat("    "), "{.strong Std. error}: {round(calc_stderror(x$eif_ate), 4)}")
	cli::cli_text(cat("        "), "{.strong 95% CI}: ({round(calc_ci(x$ate, x$eif_ate)[1], 4)}, {round(calc_ci(x$ate, x$eif_ate)[2], 4)})")
	cli::cli_h3("{.emph Path: A -> Y}")
	cli::cli_text(cat("      "), "{.strong Estimate}: {round(x$p1, 4)}")
	cli::cli_text(cat("    "), "{.strong Std. error}: {round(calc_stderror(x$eif_p1), 4)}")
	cli::cli_text(cat("        "), "{.strong 95% CI}: ({round(calc_ci(x$p1, x$eif_p1)[1], 4)}, {round(calc_ci(x$p1, x$eif_p1)[2], 4)})")
	cli::cli_h3("{.emph Path: A -> Z -> Y}")
	cli::cli_text(cat("      "), "{.strong Estimate}: {round(x$p2, 4)}")
	cli::cli_text(cat("    "), "{.strong Std. error}: {round(calc_stderror(x$eif_p2), 4)}")
	cli::cli_text(cat("        "), "{.strong 95% CI}: ({round(calc_ci(x$p2, x$eif_p2)[1], 4)}, {round(calc_ci(x$p2, x$eif_p2)[2], 4)})")
	cli::cli_h3("{.emph Path: A -> Z -> M -> Y}")
	cli::cli_text(cat("      "), "{.strong Estimate}: {round(x$p3, 4)}")
	cli::cli_text(cat("    "), "{.strong Std. error}: {round(calc_stderror(x$eif_p3), 4)}")
	cli::cli_text(cat("        "), "{.strong 95% CI}: ({round(calc_ci(x$p3, x$eif_p3)[1], 4)}, {round(calc_ci(x$p3, x$eif_p3)[2], 4)})")
	cli::cli_h3("{.emph Path: A -> M -> Y}")
	cli::cli_text(cat("      "), "{.strong Estimate}: {round(x$p4, 4)}")
	cli::cli_text(cat("    "), "{.strong Std. error}: {round(calc_stderror(x$eif_p4), 4)}")
	cli::cli_text(cat("        "), "{.strong 95% CI}: ({round(calc_ci(x$p4, x$eif_p4)[1], 4)}, {round(calc_ci(x$p4, x$eif_p4)[2], 4)})")
	cli::cli_h3("{.emph Intermediate Confounding}")
	cli::cli_text(cat("      "), "{.strong Estimate}: {round(x$intermediate_confounding, 4)}")
	cli::cli_text(cat("    "), "{.strong Std. error}: {round(calc_stderror(x$eif_intermediate_confounding), 4)}")
	cli::cli_text(cat("        "), "{.strong 95% CI}: ({round(calc_ci(x$intermediate_confounding, x$eif_intermediate_confounding)[1], 4)}, {round(calc_ci(x$intermediate_confounding, x$eif_intermediate_confounding)[2], 4)})")
}
